see source code

diff --git a/addframe b/addframe
--- a/addframe
+++ b/addframe
@@ -1,27 +1,27 @@
 #! /bin/bash
-files=`ls $1`
-length="1280"	# 画像長辺サイズ
-top="32"		# 上辺幅
-left="32"		# 左辺幅
-right="32"		# 右辺幅
-bottom="128"	# 下辺幅
+files=`ls "${1}"`
 
 if [ $# -lt 2 ]; then
 	echo "Usage :"
 	echo "    addframe <filename> <output_directory>"
 	echo "        filename : you can use wildcards."
 	echo "        output_firectory : output directory name"
-	exit
+	exit 0
 fi
 
-addExifData() {
+if [ ! -d ${2} ]; then
+	echo "Not found directory!! Specify an existing directory."
+	exit 1
+fi
+
+addExifData() { # {{{
 	copyright=`exiftool -s -Copyright -T $1`
 	copyright=${copyright}" \( OrzBruford \)"
 	date=`exiftool -s -DateTimeOriginal -T $1`
 	make=`exiftool -s -Make -T $1`
 	camera=`exiftool -s -Model -T $1`
 	lens=`exiftool -s -LensModel -T $1`
-	if [ "${lens}" == "" ]; then
+	if [ "${lens}" == "" -o "${lens}" == "-" ]; then
 		lens=`exiftool -s -LensID -T $1`
 	fi
 	iso=`exiftool -s -ISO -T $1`
@@ -36,59 +36,87 @@ addExifData() {
 			-gravity south \
 			-annotate +0+64 "Shot on ${camera}" \
 			-quality 100 \
-			tmp2.webp \
-			tmp3.webp
-	rm tmp2.webp
+			tmp3.webp \
+			tmp4.webp
+	rm tmp3.webp
 	convert -font ${font} \
 			-pointsize "16" \
 			-fill black \
 			-gravity south \
 			-annotate +0+40 "${make}" \
 			-quality 100 \
-			tmp3.webp \
-			tmp4.webp
-	rm tmp3.webp
+			tmp4.webp \
+			tmp5.webp
+	rm tmp4.webp
 	convert -font ${font} \
 			-pointsize "16" \
 			-fill "#838383" \
 			-gravity south \
 			-annotate +0+16 "$lens f${fnumber} ${ss}s ISO${iso}" \
 			-quality 100 \
-			tmp4.webp \
+			tmp5.webp \
 			${2}"/"${1}
-	rm tmp4.webp
-}
+	rm tmp5.webp
+} # }}}
 
-files=`ls ${1}`
-for tfile in ${files}
-do
-	width=`identify -format '%w' $tfile`
-	height=`identify -format '%h' $tfile`
+rotateImage() { # {{{
+	orient=`exiftool -s -Orientation -T "${1}"`
+	flg=`expr "${orient}" : "^Rotate"`
+	if [ ${flg} -ne 0 ]; then
+		angle=`echo ${orient} | cut -d " " -f 2`
+		convert "${1}" -rotate "${angle}" -orient undefined -quality 100 tmp1.webp
+	else
+		convert "${1}" -quality 100 tmp1.webp
+	fi
+} # }}}
+
+addframe() { # {{{
+	length="1280"	# 画像長辺サイズ
+	top="32"		# 上辺幅
+	left="32"		# 左辺幅
+	right="32"		# 右辺幅
+	bottom="128"	# 下辺幅
+
+	width=`identify -format '%w' tmp1.webp`
+	height=`identify -format '%h' tmp1.webp`
 	if [ $width -gt $height ]; then
-		convert "$tfile" \
+		convert tmp1.webp \
 			-resize "${length}x" \
 			-mattecolor "#fff" \
 			-splice ${left}x${top} \
-			-quality 100 tmp1.webp
-		convert tmp1.webp \
+			-quality 100 tmp2.webp
+		convert tmp2.webp \
 			-gravity southeast \
 			-mattecolor "#fff" \
 			-splice ${right}x${bottom} \
-			-quality 100 tmp2.webp
+			-quality 100 tmp3.webp
 		rm tmp1.webp
+		rm tmp2.webp
 	else
-		convert "$tfile" \
+		convert tmp1.webp \
 			-resize "x${length}" \
 			-mattecolor "#fff" \
 			-splice ${left}x${top} \
-			-quality 100 tmp1.webp
-		convert tmp1.webp \
+			-quality 100 tmp2.webp
+		convert tmp2.webp \
 			-gravity southeast \
 			-mattecolor "#fff" \
 			-splice ${right}x${bottom} \
-			-quality 100 tmp2.webp
+			-quality 100 tmp3.webp
 		rm tmp1.webp
+		rm tmp2.webp
 	fi
-	addExifData ${tfile} ${2}
+} # }}}
+
+for tfile in ${files}
+do
+	# 回転情報含有時処理 output tmp1.webp
+	rotateImage "${tfile}"
+
+	# フレーム付加 output tmp3.webp
+	addframe
+
+	# Exif データ貼り付け
+	addExifData "${tfile}" "${2}"
 done
 
